accessing
explanation: anException

	explanation := anException